;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	hungry-delete-backward
	hungry-delete-forward
	org-ctrl-c-minus
	org-metaup
	org-self-insert-command
	org-yank
	))

(setq mc/cmds-to-run-once
      '(
	mouse-set-region
	org-cycle
	))
